---
- hosts: ansible01
  gather_facts: no
  connection: local
  tasks:
    - command: whoami
      register: whoami
    - command: 'cat /root/.ssh/test_id_rsa'
      register: testrsa
      
    - debug:
        var: whoami.stdout
    - debug:
        var: testrsa.stdout
