---
- hosts: localhost
  gather_facts: no
  connection: ssh
  tasks:
    - command: whoami
      register: whoami
    - command: 'cat /root/.ssh/test_id_rsa'
      become: yes
      become_method: su
      register: testrsa
      
    - debug:
        var: whoami.stdout
    - debug:
        var: testrsa.stdout
