---
- hosts: localhost
  gather_facts: no
  connection: ssh
  become: yes
  become_method: sudo
  remote_user: root
  ansible_user: root
  tasks:
    - command: whoami
      register: whoami
    - command: 'cat /root/.ssh/test_id_rsa'
      register: testrsa
      
    - debug:
        var: whoami.stdout
    - debug:
        var: testrsa.stdout
