---
- name: Create objects only on the active DG member
  hosts: my_dg
  gather_facts: False
  connection: local
  vars:
    provider:
      password: "{{ BIGIP_password }}"
      server: "{{ BIGIP_server }}"
      user: "{{ BIGIP_username }}"
      validate_certs: False

  tasks:
    - name: Collect bigip facts
      bigip_device_facts:
        gather_subset: devices
        provider: "{{ provider }}"
        server_port: "{{ server_port }}"
      register: devices

    - block:
      - name: Create node1
        bigip_node:
          provider: "{{ provider }}"
          host: "{{ BIGIP_server }}"
          name: "{{ BIGIP_server }}"
          server_port: "{{ server_port }}"

#      - name: Create node2
#        bigip_node:
#          provider: "{{ provider }}"
#          host: "10.10.10.11"
#          name: "10.10.10.11"

      - name: Create pool
        bigip_pool:
          provider: "{{ provider }}"
          lb_method: "round-robin"
          monitors: http
          name: "{{ BIGIP_pool_name }}"
          server_port: "{{ server_port }}"

      - name: Add nodes to pool
        bigip_pool_member:
          provider: "{{ provider }}"
          server_port: "{{ server_port }}"         
#          host: "{{ item.host }}"
#          name: "{{ item.host }}"
#          host: "{{ BIGIP_lb_host }}"
#          name: "{{ BIGIP_lb_host }}"
          host: "{{ mcms_test }}"
          name: "{{ mcms_test }}"
          pool: "{{ BIGIP_pool_name }}"
          reuse_nodes: no
          port: "80"
        loop: "{{ mcms_test }}"
#        loop:
#          - host: "192.168.132.241"
#          - host: "192.168.132.242"
#          - host: "192.168.132.243"
      
#      - name: Create a virtual server
#        bigip_virtual_server:
#          provider: "{{ provider }}"
#          name: "vip1"
#          destination: "172.31.10.10"
#          port: 80
#          snat: "Automap"
#          all_profiles:
#            - http
#          pool: "pool1"
#        notify:
#          - Save the running configuration to disk
#          - Sync configuration from device to group
#      when: inventory_hostname == (devices.devices | selectattr('failover_state', 'search', 'active') | list | first).name

#  handlers:
#    - name: Save the running configuration to disk
#      bigip_config:
#       provider: "{{ provider }}"
#        save: yes

#    - name: Sync configuration from device to group
#      bigip_configsync_action:
#        provider: "{{ provider }}"
#        device_group: "{{ dg_name }}"
#        sync_device_to_group: yes
