---
# httpd is handled by the base-apache role upstream
- name: Install php and git
  become: yes
  become_method: sudo
  yum: name={{ item }} state=present
  with_items:
   - php
   - php-mysql
   - git

- name: Configure SELinux to allow httpd to connect to remote database
  become: yes
  become_method: sudo
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes
  when: sestatus.rc != 0

- name: Copy the code from repository
  become: yes
  become_method: sudo
  git: repo={{ repository }} version={{ webapp_version }} dest=/var/www/html/ force=yes
 
- name: Open firewalld port http in running configuration
  become: yes
  become_method: sudo
  firewalld: zone=public service=http permanent=false state=enabled

 
- name: Open firewalld port http in permanent configuration
  become: yes
  become_method: sudo
  firewalld: zone=public service=http permanent=true state=enabled

- name: Open firewalld port https in running configuration
  become: yes
  become_method: sudo
  firewalld: zone=public service=https permanent=false state=enabled

- name: Open firewalld port https in permanent configuration
  become: yes
  become_method: sudo
  firewalld: zone=public service=https permanent=true state=enabled
